Added input box and submit button
RichmondCroft/richmondcroft.com pull request #3
Opened 2022-04-20 13:43 UTC by shauryatripaathi

### Changes

- Created new branch named features-email.
- Added input boxes and submit button.
- Added style.css to input box.

2022-04-28 14:40 UTC, t-divya requested changes

2022-04-28 14:40 UTC, t-divya commented on src/Header/Contact/index.js
>  }
Please format the file you can remove extra spaces between elements

2022-04-28 14:40 UTC, t-divya commented on src/Header/Contact/style.css
> +    height: 200px;
You can decrease the height of the box a bit I think around 150 would be fine it looks bit long?

2022-04-28 14:40 UTC, t-divya commented on src/NavigationMenu/index.js
please format the document

2022-04-28 14:46 UTC, t-divya requested changes
changes requested

2022-04-29 13:13 UTC, t-divya requested changes
pls check requested changes

2022-04-29 13:13 UTC, t-divya commented on src/NavigationMenu/index.js
> +                <Route path='/contact' element={<Contact />}></Route>
spacing can be removed

2022-04-29 13:16 UTC, t-divya requested changes
extra space

2022-04-29 13:16 UTC, t-divya commented on src/Layout/index.js
>          <>
extra space

2022-04-30 12:39 UTC, digvijayu commented
![image](https://user-images.githubusercontent.com/7867644/166105961-5654f69e-1bfa-4dae-b023-f202014d84c1.png)
- Button should be bigger
- placeholders missing
- Border color doesn't look the same

2022-05-03 13:23 UTC, t-divya approved these changes
ok looks good to me

2022-05-04 10:40 UTC, merged