End to end testing
RichmondCroft/richmondcroft.com pull request #5
Opened 2022-05-07 14:19 UTC by shauryatripaathi

### Update

> Cypress testing installed

> Commands added to test Richmond Croft Website

> Test will check :
    - Page Loading properly
    - Clickable Links
    - Email-Id ,Subject , Textarea.   
    - Submit Button.

2022-05-07 16:12 UTC, t-divya requested changes

2022-05-07 16:12 UTC, t-divya commented on cypress/plugins/index.js
> +}
pls remove comments or just remove file that is not used.

2022-05-07 16:12 UTC, t-divya commented on cypress/support/commands.js
> +// Cypress.Commands.overwrite('visit', (originalFn, url, options) => { ... })
pls remove the commented file not used.

2022-05-07 16:12 UTC, t-divya commented on cypress/support/index.js
> +// require('./commands')
pls remove the files that are not used

2022-05-09 21:38 UTC, t-divya approved these changes

2022-05-09 21:43 UTC, digvijayu approved these changes

2022-05-10 07:18 UTC, merged